### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mspasov**
Cleans the project from .DS_Store files. Add .DS_Store to exceptions.
Removes duplicate sources.

### CODE REVIEW

**Comment by Kamran-Soomro** [comment]
Thanks Martin to point out this issue. I will fix it on Monday.

Regards,
Kamran

**Comment by mspasov** [comment]
Seems you have decided to reimplement the changes yourself, merging was the easier option imho.

There are several issues I've found in the source that should be addressed:
- missing super calls various view methods (fix is here 424a9784cda7c3064d6a0b5a6bc618f98690efb5).
- actually the whole source code was included twice, cf2fc15083edbd8aca4545c417547e40f767beb2 fixes it.

Should I rebase for easier merge?

**Comment by Kamran-Soomro** [comment]
Thanks Martin, I appreciate your suggestions and I have fixed by removing duplicate code, included super calls and also now you can enjoy new code uploaded for UART Remote control.
This time I have fixed things by uploading myself but in future I am looking forward to merge with your suggestions.
Also looking forward more suggestions from you in future.

Regards,
Kamran

**Comment by mspasov** [comment]
Great. I'll close this PR.

**Pull request closed without merging**
